### ISSUE TITLE
Update our Icon to the new school picture 

### ISSUE THREAD

**Issue by jawinch** [ClevelandHighSchool/clevelandhighschool.github.io#120]
<img width="290" alt="Cleveland Highschool new icon" src="https://user-images.githubusercontent.com/33964419/66079128-50dac080-e518-11e9-8030-7b9a7b654bff.png">

**Comment by jawinch** [comment]
I'll work on making the background transparent, resizing, and turning it into an .ico file.

Edit: pull request created.

**Comment by ClevelandHighSchool** [comment]
Thanks

**Comment by jawinch** [comment]
The icon doesn't seem to have changed after a merge. Don't know why since there should only be one favicon.ico in the folder now. It may be related to the new one being 32x32 instead of the original 16x16, but it should still work. I don't know if I should make another pull request to change it to a 16x16 so i'll just upload it here through drive. [https://drive.google.com/file/d/1K3OFURsMRolnEm6pkzDb465rzBreMfWM/view?usp=sharing](url)
